config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :cocktails, only: [ :index, :show, :create, :new ] do
  resources :doses, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses,  dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name,  presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail,  presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name,  presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]


  def index
    @cocktails= Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end


  def create
    cocktail = Cocktail.new(cocktail_params)
    if cocktail.save
      redirect_to cocktail_path(cocktail)
    else
      render :new
    end
  end

  private
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new

  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail = dose.cocktail
    dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<ul>
  <% @cocktails.each do |cocktail|  %>
  <li>
    <%= link_to cocktail.name, cocktail_path(cocktail) %>
  </li>
  <% end %>
</ul>

<%= link_to "Create New Cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<strong> <%= @cocktail.name %> </strong>

  <ul>
    <% @cocktail.doses.each do |dose|  %>
    <li>
      <%= dose.description %> of <%= dose.ingredient.name  %> -- <%= link_to "Delete", cocktail_dose_path(@cocktail, dose), method: :delete %>
    </li>


   <% end  %>
 </ul>

<h2>Add a dose</h2>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>

  <%= f.submit %>

<% end %>

<%= link_to "All Cocktals", cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>